#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TARGET_FPS 60U
#define FIXED_TIMESTEP_MS 16U
#define MAX_INPUT_BUFFER_FRAMES 3U
#define AI_TIME_BUDGET_US 1000U
#define MIN_ARENA_WIDTH 16U
#define MAX_ARENA_WIDTH 256U
#define MIN_ARENA_HEIGHT 8U
#define MAX_ARENA_HEIGHT 128U
#define MAX_ROUND_TIME_SECONDS 180U
#define MOMENTUM_DECAY_FRAMES 60U
#define SWORD_REACH_BONUS 1.1f
#define PARRIES_FOR_SWORD_EVOLUTION 3U

#endif
